"""Generate committed LVGL 9.6 4-bpp subsets; normal builds need no Pillow."""
from pathlib import Path
import hashlib
import subprocess
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/fonts/Montserrat.ttf"
SHA256 = "1e2c44ef8c956ed66998649d8c832d221e22c04eaab63c044f18eb05d1c63b7c"
LATIN = sorted(set(range(32, 127)) | set(range(160, 256)) |
               {ord(c) for c in "ĀāĆćČčĐđĞğıŁłŃńŐőŘřŚśŞşŠšŰűŹźŻżŽž’–—…"})


def generate(size, points, name):
    font = ImageFont.truetype(str(SOURCE), size)
    font.set_variation_by_axes([500])
    bitmap, descriptors = bytearray(), [(0, 0, 0, 0, 0, 0)]
    above = below = 0
    for cp in points:
        letter = chr(cp)
        left, top, right, bottom = font.getbbox(letter, anchor="ls")
        width, height = right - left, bottom - top
        above, below = max(above, -top), max(below, bottom)
        descriptors.append((len(bitmap), round(font.getlength(letter) * 16),
                            width, height, left, -bottom))
        image = Image.new("L", (max(1, width), max(1, height)))
        ImageDraw.Draw(image).text((-left, -top), letter, font=font, fill=255, anchor="ls")
        pixels = [round(v * 15 / 255) for v in image.get_flattened_data()] if width and height else []
        for offset in range(0, len(pixels), 2):
            bitmap.append((pixels[offset] << 4) | (pixels[offset + 1] if offset + 1 < len(pixels) else 0))
    rows = ["/* Generated by scripts/build_fonts.py; Montserrat, SIL OFL 1.1. */",
            '#include "lvgl.h"', "static const uint8_t glyph_bitmap[] = {"]
    rows += ["  " + ", ".join(f"0x{v:02x}" for v in bitmap[i:i+16]) + "," for i in range(0, len(bitmap), 16)]
    rows += ["};", "static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {"]
    for index, advance, width, height, x, y in descriptors:
        rows.append(f"  {{.bitmap_index={index}, .adv_w={advance}, .box_w={width}, .box_h={height}, .ofs_x={x}, .ofs_y={y}}},")
    start = points[0]
    rows += ["};", "static const uint16_t unicode_list[] = {" + ",".join(str(cp-start) for cp in points) + "};",
             "static const lv_font_fmt_txt_cmap_t cmaps[] = {",
             f"  {{.range_start={start}, .range_length={points[-1]-start+1}, .glyph_id_start=1, .unicode_list=unicode_list, .list_length={len(points)}, .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}", "};",
             "static const lv_font_fmt_txt_dsc_t font_dsc = {.glyph_bitmap=glyph_bitmap, .glyph_dsc=glyph_dsc, .cmaps=cmaps, .cmap_num=1, .bpp=4, .bitmap_format=LV_FONT_FMT_TXT_PLAIN};",
             "static bool glyph(const lv_font_t* font, lv_font_glyph_dsc_t* out, uint32_t cp, uint32_t next) {",
             "  return lv_font_get_glyph_dsc_fmt_txt(font, out, cp, next) || lv_font_get_glyph_dsc_fmt_txt(font, out, '?', 0);", "}",
             f"const lv_font_t {name} = {{.get_glyph_dsc=glyph, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt, .line_height={above+below}, .base_line={below}, .cap_height={-font.getbbox('H', anchor='ls')[1]}, .x_height={-font.getbbox('x', anchor='ls')[1]}, .static_bitmap=1, .dsc=&font_dsc}};", ""]
    destination = ROOT / f"components/ui/fonts/{name}.c"
    destination.write_text("\n".join(rows))
    formatter = ROOT / ".venv-tools/bin/clang-format"
    if formatter.exists():
        subprocess.run([str(formatter), "-i", str(destination)], check=True)
    print(f"{name}: {len(points)} glyphs, bitmap {len(bitmap)} B, line {above+below} px")


if __name__ == "__main__":
    if hashlib.sha256(SOURCE.read_bytes()).hexdigest() != SHA256:
        raise SystemExit("Font source hash differs; review source/licence before regenerating")
    for px in (10, 14, 18):
        generate(px, LATIN, f"ui_font_text_{px}")
    generate(28, sorted({ord(c) for c in " 0123456789:-?"}), "ui_font_score_28")
